import subprocess
import sys

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

try:
    import docx
except ImportError:
    install('python-docx')
    import docx

from docx import Document
from docx.shared import Pt, Inches

def add_heading(doc, text, level=1):
    doc.add_heading(text, level=level)

def add_paragraph(doc, text):
    doc.add_paragraph(text)

def generate_report():
    doc = Document()
    add_heading(doc, 'Fantasy Football Dashboard - Application Report', 0)
    add_paragraph(doc, "This document serves as a comprehensive guide to every screen, table, and metric within the Fantasy Football Dashboard application. It breaks down how the backend calculates each metric, what data sources are used, and how the metrics are presented on the frontend to ensure data accuracy and transparency.\n")

    # GLOBAL DATA PIPELINE
    add_heading(doc, '1. Global Data Architecture & Synchronization', 1)
    add_paragraph(doc, "The application's intelligence relies on merging data from two primary sources: the Sleeper Fantasy API and the NFLVerse/nflfastR statistical engines.")
    doc.add_paragraph("• Sleeper API: Provides league metadata, rosters, historical matchups, brackets, and active player IDs.", style='List Bullet')
    doc.add_paragraph("• NFLVerse (Player Advanced Stats): Provides weekly and seasonal NFL statistics (PPR fantasy points, passing/rushing stats) bound to unique GSIS IDs.", style='List Bullet')
    add_paragraph(doc, "Calculations depend on mapping Sleeper's internal Player IDs to actual on-field statistics using the database tables: rosters, player_advanced_stats, sleeper_transactions, and matchups_history.\n")

    # LEAGUE ANALYZER
    add_heading(doc, '2. League Analyzer Screen', 1)
    add_paragraph(doc, "The League Analyzer provides a macro-view of all teams, their total scoring output, and relative positional strengths.")
    
    add_heading(doc, 'Team Power Rankings Table', 2)
    doc.add_paragraph("• Roster: The team's display name, resolved from Sleeper User mappings.", style='List Bullet')
    doc.add_paragraph("• Offense: The sum of fantasy points generated by players currently on the team's roster for the 2024/2025 seasons. Formula: SUM(fantasy_points_ppr) for all player_ids in roster.players.", style='List Bullet')
    doc.add_paragraph("• Age: The weighted average age of the roster's active players.", style='List Bullet')
    doc.add_paragraph("• Positional Heatmap: A color-coded breakdown of the team's total points clustered by position (QB, RB, WR, TE).", style='List Bullet')

    add_heading(doc, 'True Power Matrix (Scatter Chart)', 2)
    doc.add_paragraph("• X-Axis (Team Age): The average age of the roster.", style='List Bullet')
    doc.add_paragraph("• Y-Axis (Team Output): The total combined PPR points for all players on the roster.", style='List Bullet')
    doc.add_paragraph("• Quadrants: \n  - Dynasty Juggernaut (Top Left: Young & High Scoring)\n  - Win Now (Top Right: Old & High Scoring)\n  - Productive Struggle (Bottom Left: Young & Low Scoring)\n  - Rebuilding (Bottom Right: Old & Low Scoring)", style='List Bullet')

    # DYNASTY ROOM
    add_heading(doc, '3. Dynasty Room Screen', 1)
    add_paragraph(doc, "The Dynasty Room offers an isolated deep-dive into a specific manager's team composition, historical success, and individual player performance.")

    add_heading(doc, 'Active Roster Table', 2)
    doc.add_paragraph("• Columns: Player Name, Position, Age, Rank (currently mapped to external dynasty ranks if synced), and Output (Points).", style='List Bullet')
    doc.add_paragraph("• Calculation: Performs a SQL IN query fetching PlayerAdvancedStats where player_id exists in the team's current Sleeper roster JSON payload.", style='List Bullet')

    add_heading(doc, 'Positional Strength vs League Avg (Radar Chart)', 2)
    doc.add_paragraph("• Purpose: Visualizes if a team is over-indexing or under-indexing at specific positions compared to the rest of the league.", style='List Bullet')
    doc.add_paragraph("• Calculation: \n  1. Calculate Team Positional Output: Sum of average points per game for all QBs, RBs, WRs, TEs, and FLEX (RB+WR+TE) on the roster.\n  2. Calculate League Average Positional Output: Sum of all points for all rosters divided by the number of teams.\n  3. Normalization: Team Score = (Team Positional Output / League Average Positional Output) * 100.\n  4. Chart Scaling: The League Average forms a perfect hexagon at '100'. The Team's polygon stretches outward (>100) or inward (<100).", style='List Bullet')

    add_heading(doc, 'Roster Health (Age Demographics Pie Chart)', 2)
    doc.add_paragraph("• Calculation: Groups roster players into three buckets based on age thresholds: Under 24, 25-28, and Over 28.", style='List Bullet')

    add_heading(doc, 'Key Dynasty Metrics (Cards)', 2)
    doc.add_paragraph("• Biggest Heartbreak: Finds the matchup (from MatchupHistory table) with the smallest point differential where is_win == 0. Excludes matchups where both teams scored 0.0 (byes/unplayed).", style='List Bullet')
    doc.add_paragraph("• Avg Margin of Victory: Sum of all point differentials where is_win == 1 divided by the total number of wins.", style='List Bullet')
    doc.add_paragraph("• Total Trades: Counts the number of times the team's roster_id appears in the sleeper_transactions table where type == 'trade'.", style='List Bullet')
    doc.add_paragraph("• Waiver Wire Adds: Counts the number of waiver/free-agent acquisitions in the sleeper_transactions table for the roster.", style='List Bullet')

    add_heading(doc, 'League Record Book (Hall of Fame)', 2)
    doc.add_paragraph("• Purpose: Displays the historical podium finishes for every season.", style='List Bullet')
    doc.add_paragraph("• Calculation: Iterates backward through Sleeper's previous_league_id. Fetches the winners_bracket and losers_bracket.\n  - Champion: Winner of the game where p=1 in the winners bracket.\n  - 2nd Place: Loser of the game where p=1 in the winners bracket.\n  - 3rd Place: Winner of the game where p=3 in the winners bracket.\n  - Last Place: Loser of the game with the highest 'p' value in the losers bracket.", style='List Bullet')

    # PLAYER DATABASE
    add_heading(doc, '4. Player Database & Cross-Reference', 1)
    doc.add_paragraph("• Player Database Table: A massive paginated table pulling directly from PlayerAdvancedStats. Displays Passing Yards, Touchdowns, Rushing, Receptions, etc. Sortable by points and age.", style='List Bullet')
    doc.add_paragraph("• Cross-Reference Analyzer: Allows users to map two variables against each other (e.g., Age vs Targets, Passing Yards vs Interceptions) to find undervalued players in the market.", style='List Bullet')

    doc.save('Fantasy_Football_Dashboard_Report.docx')
    print("Report generated successfully as Fantasy_Football_Dashboard_Report.docx")

if __name__ == "__main__":
    generate_report()
