import React from 'react';

export default function GlossaryPage() {
  const terms = [
    {
      term: 'aDOT (Average Depth of Target)',
      definition: 'The average distance downfield that a player is targeted. It measures how deep a receiver is running their routes on average when thrown to.',
      category: 'Receiving'
    },
    {
      term: 'EPA (Expected Points Added)',
      definition: 'A measure of how much a specific play increased or decreased the expected point value of a drive. It takes down, distance, and field position into account to measure context-independent value.',
      category: 'Advanced'
    },
    {
      term: 'YOE (Yards Over Expected)',
      definition: 'The difference between actual yards gained and the expected yards based on player tracking data and game situation.',
      category: 'Advanced'
    },
    {
      term: 'CPOE (Completion Percentage Over Expected)',
      definition: 'The difference between a quarterback\'s actual completion percentage and their expected completion percentage, based on the difficulty of the throws they attempted.',
      category: 'Passing'
    },
    {
      term: 'YPRR (Yards Per Route Run)',
      definition: 'The number of receiving yards a player gains divided by the number of passing routes they run. This is a strong indicator of receiving efficiency.',
      category: 'Receiving'
    },
    {
      term: 'Target Rate',
      definition: 'The percentage of a player\'s routes run where they were targeted with a pass.',
      category: 'Receiving'
    },
    {
      term: 'Catch Rate / Catch %',
      definition: 'The percentage of targets that a receiver successfully catches.',
      category: 'Receiving'
    },
    {
      term: 'Redzone Targets / RZ Rush',
      definition: 'Opportunities a player receives when the offense is inside the opponent\'s 20-yard line. This is a strong predictor of touchdown scoring potential.',
      category: 'Usage'
    },
    {
      term: 'PPG (Points Per Game) / Fan Pts',
      definition: 'The average number of fantasy points a player scores per game played. Fan Pts refers to total fantasy points.',
      category: 'Usage'
    },
    {
      term: 'YAC/Rec (Yards After Catch per Reception)',
      definition: 'The average amount of rushing yards a receiver gains after making a catch. Highlights a player\'s elusiveness and open-field ability.',
      category: 'Receiving'
    },
    {
      term: 'Air Yds/Tgt (Air Yards per Target)',
      definition: 'The total distance a football travels past the line of scrimmage on a pass attempt, divided by the total number of targets.',
      category: 'Receiving'
    },
    {
      term: 'Snap % / Offense Pct',
      definition: 'The percentage of total offensive or defensive snaps a player was on the field for. Represents total opportunity.',
      category: 'Usage'
    },
    {
      term: 'Tgt (Targets)',
      definition: 'The total number of pass attempts directed at a receiver.',
      category: 'Receiving'
    },
    {
      term: 'Rec (Receptions)',
      definition: 'The total number of successfully caught passes.',
      category: 'Receiving'
    },
    {
      term: 'Yds (Yards)',
      definition: 'Total yards gained by the player either passing, rushing, or receiving.',
      category: 'Usage'
    },
    {
      term: 'G (Games Played)',
      definition: 'Total number of games the player actively participated in.',
      category: 'Usage'
    },
    {
      term: 'TFL (Tackles For Loss)',
      definition: 'When a defensive player tackles the ball carrier behind the line of scrimmage, resulting in negative yardage for the offense.',
      category: 'Defense'
    },
    {
      term: 'Pass Def (Pass Deflections)',
      definition: 'When a defensive player actively swats or knocks down a pass attempt before it reaches the intended receiver.',
      category: 'Defense'
    },
    {
      term: 'Pressures / QB Hits',
      definition: 'The sum of sacks and quarterback hits generated by a defensive player. Highlights disruptive pass-rushing ability.',
      category: 'Defense'
    }
  ];

  const categories = Array.from(new Set(terms.map(t => t.category)));

  return (
    <div className="max-w-4xl mx-auto space-y-8 h-full flex flex-col py-8 px-4">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-white mb-2">Metrics Glossary</h1>
        <p className="text-slate-400">Definitions and explanations for the advanced analytics metrics used throughout Waiver WireTap.</p>
      </div>

      <div className="space-y-8">
        {categories.map(category => (
          <div key={category} className="space-y-4">
            <h2 className="text-2xl font-semibold text-indigo-400 border-b border-slate-800 pb-2">{category}</h2>
            <div className="grid gap-4">
              {terms.filter(t => t.category === category).map(term => (
                <div key={term.term} className="bg-slate-900 border border-slate-800 rounded-xl p-6 hover:border-slate-700 transition-colors">
                  <h3 className="text-xl font-bold text-white mb-2">{term.term}</h3>
                  <p className="text-slate-400 leading-relaxed">{term.definition}</p>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
